//! T56/T76 FPGA algorithm bitstream loading.
//!
//! The T56 and T76 programmers require FPGA bitstream algorithms to be
//! uploaded from the host before most chip operations.  These bitstreams
//! are stored in `algorithm.xml` (generated by `dump-alg-minipro.bash`
//! from the official XGPro software) as base64-encoded gzip-compressed
//! blobs.
//!
//! This module mirrors the C `get_algorithm()` function in `database.c`:
//!
//! 1. Compute the algorithm name from the device's `protocol_id` and
//!    `variant` (with special cases for ATmega ICSP, AT89C ICSP, eMMC
//!    voltage selection, and reversed packages).
//! 2. Parse `algorithm.xml` to find the `<algorithm>` entry with that name
//!    in the `<algorithms_T56>` or `<algorithms_T76>` section.
//! 3. Base64-decode the `bitstream` attribute.
//! 4. Gunzip the result.
//! 5. Verify the embedded CRC32.
//! 6. For T76: perform a second-level zero-run decompression.

use std::io::Read;
use std::path::Path;

use base64::Engine;
use crc::{Crc, CRC_32_ISO_HDLC};
use flate2::read::GzDecoder;
use quick_xml::events::Event;
use quick_xml::Reader;

use crate::device::{Device, ProgrammerModel};
use crate::error::MiniproError;

// ── Algorithm name prefix table (indexed by protocol_id - 1) ─────────────────
//
// Maps protocol_id to the prefix string used to look up the algorithm in
// algorithm.xml.  The final name is `<prefix><NN>` where NN is the
// algorithm number (high byte of `variant`) formatted as uppercase hex.
//
// Empty strings correspond to protocol IDs that have no algorithm entries
// (e.g. PIC16C, SM89, SM59, SM39).
const ALGO_TABLE: [&str; 53] = [
    "IIC24C",   // 0x01
    "MW93ALG",  // 0x02
    "SPI25F",   // 0x03
    "AT45D",    // 0x04
    "F29EE",    // 0x05
    "W29F32P",  // 0x06
    "ROM28P",   // 0x07
    "ROM32P",   // 0x08
    "ROM40P",   // 0x09
    "R28TO32P", // 0x0A
    "ROM24P",   // 0x0B
    "ROM44",    // 0x0C
    "EE28C32P", // 0x0D
    "RAM32",    // 0x0E
    "SPI25F",   // 0x0F
    "28F32P",   // 0x10
    "FWH",      // 0x11
    "T48",      // 0x12
    "T40A",     // 0x13
    "T40B",     // 0x14
    "T88V",     // 0x15
    "PIC32X",   // 0x16
    "P18F87J",  // 0x17
    "P16F",     // 0x18
    "P18F2",    // 0x19
    "P16F5X",   // 0x1A
    "P16CX",    // 0x1B
    "",         // 0x1C (PIC16C)
    "ATMGA_",   // 0x1D
    "ATTINY_",  // 0x1E
    "AT89P20_", // 0x1F
    "",         // 0x20 (SM89)
    "AT89C_",   // 0x21
    "P87C_",    // 0x22
    "SST89_",   // 0x23
    "W78E_",    // 0x24
    "",         // 0x25 (SM59)
    "",         // 0x26 (SM39)
    "ROM24P",   // 0x27
    "ROM28P",   // 0x28
    "RAM32",    // 0x29
    "GAL16",    // 0x2A
    "GAL20",    // 0x2B
    "GAL22",    // 0x2C
    "NAND_",    // 0x2D
    "PIC32X",   // 0x2E
    "RAM36",    // 0x2F
    "KB90",     // 0x30
    "EMMC_",    // 0x31
    "VGA_",     // 0x32
    "CPLD_",    // 0x33
    "GEN_",     // 0x34
    "ITE_",     // 0x35
];

// ── Utility algorithm name tables (for logic chips and special functions) ────

const T56_UTIL_TABLE: [&str; 17] = [
    "TTL1",
    "TTL2",
    "Pindect100M",
    "STGND",
    "StPVGI",
    "uart_vga",
    "vga_11",
    "vga_21",
    "vga1024x768",
    "vga1152x864",
    "vga1280x1024",
    "vga1280x800",
    "vga1440x900",
    "vga1920x1080",
    "vga640x480",
    "vga800x600",
    "vga_hdmi",
];

const T76_UTIL_TABLE: [&str; 5] = [
    "Test_100M",
    "TestGND",
    "TestLgcDown",
    "TestLgcPull",
    "TestVcc",
];

// ── Bitstream binary layout offsets ──────────────────────────────────────────

const ALGO_SIZE_OFFSET: usize = 0x00; // u32 LE — uncompressed size (T76 level-2)
const ALGO_CRC_OFFSET: usize = 0x04; // u32 LE — CRC32 of data from offset 0x08
const ALGO_DATA_OFFSET: usize = 0x08; // Start of bitstream payload

// ── Protocol IDs requiring special name handling ─────────────────────────────

const IC2_ALG_NONE: u8 = 0x00;
const IC2_ALG_ATMGA: u8 = 0x1D;
const IC2_ALG_AT89C: u8 = 0x21;
const IC2_ALG_EMMC: u8 = 0x31;

// eMMC voltage options (from cmdopts_t.vopt in minipro.h)
pub const V_1V8: u8 = 0;
pub const V_3V3: u8 = 1;

const CRC32: Crc<u32> = Crc::<u32>::new(&CRC_32_ISO_HDLC);

// ── Public API ───────────────────────────────────────────────────────────────

/// Look up and decode the FPGA algorithm bitstream for `device` on the given
/// programmer `model`.
///
/// `icsp` selects the ICSP variant for ATmega/AT89C protocols.
/// `vopt` selects the voltage variant for eMMC (`V_1V8` or `V_3V3`).
/// `algo_path` is the path to `algorithm.xml`.
///
/// Returns an [`Algorithm`](crate::device::Algorithm) with the decoded
/// bitstream ready for upload.  Returns an error if the algorithm is not
/// found, the file is missing, or CRC verification fails.
pub fn get_algorithm(
    device: &Device,
    model: ProgrammerModel,
    icsp: bool,
    vopt: u8,
    algo_path: &Path,
) -> Result<crate::device::Algorithm, MiniproError> {
    let name = compute_algorithm_name(device, model, icsp, vopt)?;
    let base64_data = find_algorithm_in_xml(algo_path, &name, model)?;
    let bitstream = decode_bitstream(&base64_data, model)?;
    Ok(crate::device::Algorithm { name, bitstream })
}

/// Check whether a device needs an algorithm lookup (T56/T76 with a
/// non-trivial protocol or logic chip type).
pub fn needs_algorithm(device: &Device, model: ProgrammerModel) -> bool {
    match model {
        ProgrammerModel::T56 | ProgrammerModel::T76 => {}
        _ => return false,
    }
    // Logic chips (protocol_id == 0) use utility algorithms.
    // All other non-zero protocol IDs use named algorithms.
    // Chips with protocol_id 0 and chip_type Logic (0x05) need util algorithms.
    device.protocol_id != IC2_ALG_NONE || device.chip_type == crate::device::ChipType::Logic as u32
}

// ── Name computation ─────────────────────────────────────────────────────────

/// Compute the algorithm name that `algorithm.xml` uses for this device.
///
/// Mirrors the C `get_algorithm()` name-building logic in `database.c`.
fn compute_algorithm_name(
    device: &Device,
    model: ProgrammerModel,
    icsp: bool,
    vopt: u8,
) -> Result<String, MiniproError> {
    let algo_number = (device.variant >> 8) as u8;

    // Select the utility table based on programmer model.
    let (util_table, _): (&[&str], ()) = match model {
        ProgrammerModel::T56 => (&T56_UTIL_TABLE, ()),
        ProgrammerModel::T76 => (&T76_UTIL_TABLE, ()),
        _ => {
            return Err(MiniproError::UnsupportedOperation);
        }
    };

    // Validate algorithm number range.
    if device.protocol_id != IC2_ALG_NONE {
        let idx = (device.protocol_id as usize).checked_sub(1);
        let entry = match idx {
            Some(i) if i < ALGO_TABLE.len() => ALGO_TABLE[i],
            _ => {
                return Err(MiniproError::Protocol(format!(
                    "Invalid algorithm protocol_id 0x{:02X}",
                    device.protocol_id
                )));
            }
        };
        if entry.is_empty() {
            return Err(MiniproError::Protocol(format!(
                "No algorithm prefix for protocol_id 0x{:02X}",
                device.protocol_id
            )));
        }
    } else if algo_number as usize >= util_table.len() {
        return Err(MiniproError::Protocol(format!(
            "Invalid utility algorithm number {}",
            algo_number
        )));
    }

    if device.protocol_id != IC2_ALG_NONE {
        // Named algorithm: prefix + variant hex number (with special cases).
        let idx = (device.protocol_id - 1) as usize;
        let prefix = ALGO_TABLE[idx];
        let mut name = String::from(prefix);

        match device.protocol_id {
            IC2_ALG_ATMGA => {
                // ATmega: ICSP uses "11S" suffix, otherwise hex algo number.
                if icsp {
                    name.push_str("11S");
                } else {
                    name.push_str(&format!("{:02X}", algo_number));
                }
            }
            IC2_ALG_AT89C => {
                // AT89C: ICSP uses "2S" suffix, otherwise hex algo number.
                if icsp {
                    name.push_str("2S");
                } else {
                    name.push_str(&format!("{:02X}", algo_number));
                }
            }
            IC2_ALG_EMMC => {
                // eMMC: lowercase hex algo number + voltage suffix.
                name.push_str(&format!("{:02x}", algo_number));
                name.push_str(if vopt == V_1V8 { "_18" } else { "_33" });
            }
            _ => {
                name.push_str(&format!("{:02X}", algo_number));
                if device.flags.reversed_package {
                    name.push('R');
                }
            }
        }
        Ok(name)
    } else {
        // Logic / utility algorithm: look up by index.
        Ok(util_table[algo_number as usize].to_string())
    }
}

// ── XML parsing ──────────────────────────────────────────────────────────────

/// Search `algorithm.xml` for the `<algorithm name="...">` entry matching
/// `name` in the section for `model` (T56 or T76), and return the base64
/// bitstream string.
fn find_algorithm_in_xml(
    path: &Path,
    name: &str,
    model: ProgrammerModel,
) -> Result<String, MiniproError> {
    let file = std::fs::File::open(path).map_err(|e| {
        MiniproError::Xml(format!(
            "Cannot open algorithm file '{}': {}",
            path.display(),
            e
        ))
    })?;
    let mut reader = Reader::from_reader(std::io::BufReader::new(file));
    reader.config_mut().trim_text(true);

    let section_tag = match model {
        ProgrammerModel::T56 => "algorithms_T56",
        ProgrammerModel::T76 => "algorithms_T76",
        _ => return Err(MiniproError::UnsupportedOperation),
    };

    let mut buf = Vec::new();
    let mut in_section = false;
    let mut depth_in_section = 0u32;

    loop {
        match reader.read_event_into(&mut buf) {
            Ok(Event::Start(e)) => {
                let tag_name = String::from_utf8_lossy(e.name().as_ref()).into_owned();
                if tag_name == section_tag {
                    in_section = true;
                    depth_in_section = 1;
                } else if in_section {
                    depth_in_section += 1;
                }
            }
            Ok(Event::Empty(e)) => {
                let tag_name = String::from_utf8_lossy(e.name().as_ref()).into_owned();
                if in_section && tag_name == "algorithm" {
                    // Check the name attribute.
                    let mut found_name = false;
                    let mut bitstream_val = None;
                    for attr in e.attributes() {
                        let attr = match attr {
                            Ok(a) => a,
                            Err(_) => continue,
                        };
                        let key = std::str::from_utf8(attr.key.as_ref()).unwrap_or("");
                        let val = std::str::from_utf8(&attr.value).unwrap_or("");
                        if key == "name" && val == name {
                            found_name = true;
                        } else if key == "bitstream" {
                            bitstream_val = Some(val.to_string());
                        }
                    }
                    if found_name {
                        if let Some(bs) = bitstream_val {
                            return Ok(bs);
                        }
                        return Err(MiniproError::Xml(format!(
                            "Algorithm '{}' found in algorithm.xml but has no bitstream attribute",
                            name
                        )));
                    }
                }
            }
            Ok(Event::End(e)) => {
                let tag_name = String::from_utf8_lossy(e.name().as_ref()).into_owned();
                if in_section {
                    depth_in_section = depth_in_section.saturating_sub(1);
                    if tag_name == section_tag || depth_in_section == 0 {
                        in_section = false;
                    }
                }
            }
            Ok(Event::Eof) => break,
            Err(e) => {
                return Err(MiniproError::Xml(format!(
                    "XML parse error in algorithm.xml: {}",
                    e
                )));
            }
            _ => {}
        }
        buf.clear();
    }

    Err(MiniproError::Xml(format!(
        "Algorithm '{}' not found in algorithm.xml ({})",
        name, section_tag
    )))
}

// ── Bitstream decoding ───────────────────────────────────────────────────────

/// Decode the base64 + gzip bitstream, verify CRC, and (for T76) perform
/// level-2 zero-run decompression.
fn decode_bitstream(base64_data: &str, model: ProgrammerModel) -> Result<Vec<u8>, MiniproError> {
    // 1. Base64 decode.
    let gzip_data = base64::engine::general_purpose::STANDARD
        .decode(base64_data.trim())
        .map_err(|e| MiniproError::AlgorithmDecompress(format!("base64 decode error: {}", e)))?;

    // 2. Gunzip.
    let mut decoder = GzDecoder::new(&gzip_data[..]);
    let mut raw = Vec::new();
    decoder.read_to_end(&mut raw).map_err(|e| {
        MiniproError::AlgorithmDecompress(format!("gzip decompression error: {}", e))
    })?;

    // 3. Verify CRC.
    // The gzip trailer contains the uncompressed size (last 4 bytes, LE).
    let usize_gzip = u32::from_le_bytes([
        gzip_data[gzip_data.len() - 4],
        gzip_data[gzip_data.len() - 3],
        gzip_data[gzip_data.len() - 2],
        gzip_data[gzip_data.len() - 1],
    ]) as usize;

    if raw.len() != usize_gzip {
        return Err(MiniproError::AlgorithmDecompress(format!(
            "size mismatch: expected {}, got {}",
            usize_gzip,
            raw.len()
        )));
    }

    if raw.len() < ALGO_DATA_OFFSET {
        return Err(MiniproError::AlgorithmDecompress(
            "bitstream too short for header".into(),
        ));
    }

    let file_crc = u32::from_le_bytes([
        raw[ALGO_CRC_OFFSET],
        raw[ALGO_CRC_OFFSET + 1],
        raw[ALGO_CRC_OFFSET + 2],
        raw[ALGO_CRC_OFFSET + 3],
    ]);
    let data_crc = CRC32.checksum(&raw[ALGO_DATA_OFFSET..]);

    if file_crc != data_crc {
        return Err(MiniproError::AlgorithmCrc);
    }

    // 4. T56: round up to 512-byte multiple.
    if model == ProgrammerModel::T56 {
        let padded_len = raw.len() + (0x200 - (raw.len() % 0x200));
        let mut padded = raw.clone();
        padded.resize(padded_len, 0);
        return Ok(padded);
    }

    // 5. T76: level-2 zero-run decompression.
    if model == ProgrammerModel::T76 {
        return level2_decompress(&raw);
    }

    Ok(raw)
}

/// T76 level-2 decompression: the gzip-decompressed bitstream uses a simple
/// zero-run encoding on u16 values.  A non-zero u16 is copied as-is; a zero
/// u16 is followed by a count u16, and that many zero u16s are inserted.
fn level2_decompress(raw: &[u8]) -> Result<Vec<u8>, MiniproError> {
    if raw.len() < ALGO_DATA_OFFSET + 4 {
        return Err(MiniproError::AlgorithmDecompress(
            "T76 algorithm too short for level-2 decompression".into(),
        ));
    }

    // Target output size is at ALGO_SIZE_OFFSET (first 4 bytes, LE).
    let algo_size = u32::from_le_bytes([
        raw[ALGO_SIZE_OFFSET],
        raw[ALGO_SIZE_OFFSET + 1],
        raw[ALGO_SIZE_OFFSET + 2],
        raw[ALGO_SIZE_OFFSET + 3],
    ]) as usize;

    let mut out = vec![0u8; algo_size];
    let mut out_pos = 0usize;

    // Input data starts at ALGO_DATA_OFFSET, processed as u16 pairs.
    let input = &raw[ALGO_DATA_OFFSET..];
    let mut in_pos = 0usize;

    while in_pos + 2 <= input.len() && out_pos + 2 <= algo_size {
        let val = u16::from_le_bytes([input[in_pos], input[in_pos + 1]]);
        in_pos += 2;

        if val != 0 {
            out[out_pos] = (val & 0xff) as u8;
            out[out_pos + 1] = (val >> 8) as u8;
            out_pos += 2;
        } else {
            // Next u16 is the zero-run count.
            if in_pos + 2 > input.len() {
                break;
            }
            let count = u16::from_le_bytes([input[in_pos], input[in_pos + 1]]) as usize;
            in_pos += 2;
            let byte_count = count * 2;
            if out_pos + byte_count > algo_size {
                return Err(MiniproError::AlgorithmDecompress(
                    "T76 level-2 decompression overflow".into(),
                ));
            }
            // Zeros are already in the buffer from vec![0u8; algo_size].
            out_pos += byte_count;
        }
    }

    if out_pos != algo_size {
        return Err(MiniproError::AlgorithmDecompress(format!(
            "T76 level-2 decompression size mismatch: expected {}, got {}",
            algo_size, out_pos
        )));
    }

    Ok(out)
}

// ── Tests ────────────────────────────────────────────────────────────────────

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_compute_name_spi_nor() {
        // SPI25F protocol (0x03), variant 0x1100 → algo_number 0x11
        let device = Device {
            protocol_id: 0x03,
            variant: 0x1100,
            ..Default::default()
        };
        let name = compute_algorithm_name(&device, ProgrammerModel::T56, false, V_3V3).unwrap();
        assert_eq!(name, "SPI25F11");
    }

    #[test]
    fn test_compute_name_emmc_1v8() {
        // eMMC protocol (0x31), variant 0x5100 → algo_number 0x51, 1.8V
        let device = Device {
            protocol_id: 0x31,
            variant: 0x5100,
            ..Default::default()
        };
        let name = compute_algorithm_name(&device, ProgrammerModel::T76, false, V_1V8).unwrap();
        assert_eq!(name, "EMMC_51_18");
    }

    #[test]
    fn test_compute_name_emmc_3v3() {
        let device = Device {
            protocol_id: 0x31,
            variant: 0x5400,
            ..Default::default()
        };
        let name = compute_algorithm_name(&device, ProgrammerModel::T76, false, V_3V3).unwrap();
        assert_eq!(name, "EMMC_54_33");
    }

    #[test]
    fn test_compute_name_atmega_icsp() {
        // ATmega protocol (0x1D), ICSP mode
        let device = Device {
            protocol_id: 0x1D,
            variant: 0x0100,
            ..Default::default()
        };
        let name = compute_algorithm_name(&device, ProgrammerModel::T56, true, V_3V3).unwrap();
        assert_eq!(name, "ATMGA_11S");
    }

    #[test]
    fn test_compute_name_atmega_non_icsp() {
        let device = Device {
            protocol_id: 0x1D,
            variant: 0x0100,
            ..Default::default()
        };
        let name = compute_algorithm_name(&device, ProgrammerModel::T56, false, V_3V3).unwrap();
        assert_eq!(name, "ATMGA_01");
    }

    #[test]
    fn test_compute_name_reversed_package() {
        let device = Device {
            protocol_id: 0x03,
            variant: 0x1100,
            flags: crate::device::DeviceFlags {
                reversed_package: true,
                ..Default::default()
            },
            ..Default::default()
        };
        let name = compute_algorithm_name(&device, ProgrammerModel::T56, false, V_3V3).unwrap();
        assert_eq!(name, "SPI25F11R");
    }

    #[test]
    fn test_compute_name_logic_t56() {
        // Logic chip (protocol_id 0), algo_number 0 = TTL1
        let device = Device {
            protocol_id: 0x00,
            variant: 0x0000,
            chip_type: crate::device::ChipType::Logic as u32,
            ..Default::default()
        };
        let name = compute_algorithm_name(&device, ProgrammerModel::T56, false, V_3V3).unwrap();
        assert_eq!(name, "TTL1");
    }

    #[test]
    fn test_compute_name_logic_t76() {
        let device = Device {
            protocol_id: 0x00,
            variant: 0x0100, // algo_number 1 = TestGND
            chip_type: crate::device::ChipType::Logic as u32,
            ..Default::default()
        };
        let name = compute_algorithm_name(&device, ProgrammerModel::T76, false, V_3V3).unwrap();
        assert_eq!(name, "TestGND");
    }

    #[test]
    fn test_level2_decompress_basic() {
        // Construct a minimal level-2 compressed stream:
        // [0..4]  algo_size = 8 (LE32)
        // [4..8]  CRC (don't care for this test)
        // [8..10] val=0x1234 (non-zero, copy)
        // [10..12] val=0x0000 (zero, next is count)
        // [12..14] count=2 (insert 2 zero u16s = 4 bytes)
        // [14..16] val=0x5678 (non-zero, copy)
        let mut raw = vec![0u8; 16];
        raw[0..4].copy_from_slice(&8u32.to_le_bytes());
        raw[4..8].copy_from_slice(&0u32.to_le_bytes()); // CRC (ignored in test)
        raw[8..10].copy_from_slice(&0x1234u16.to_le_bytes());
        raw[10..12].copy_from_slice(&0x0000u16.to_le_bytes());
        raw[12..14].copy_from_slice(&2u16.to_le_bytes());
        raw[14..16].copy_from_slice(&0x5678u16.to_le_bytes());

        let out = level2_decompress(&raw).unwrap();
        assert_eq!(out.len(), 8);
        assert_eq!(&out[0..2], &0x1234u16.to_le_bytes());
        assert_eq!(&out[2..6], &[0, 0, 0, 0]); // 2 zero u16s
        assert_eq!(&out[6..8], &0x5678u16.to_le_bytes());
    }
}
